### Pytorch

In [2]:
import torch 

#### Calculate the dot product between two vectors each of length 3

In [3]:
V1 = torch.tensor([1, 2, 3])
V2 = torch.tensor([6, 5, 4])


# Dot product of V1 and V2
torch.dot(V1,V2)

tensor(28)

#### Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [4]:
M1 = torch.tensor(
    [
        [1,2],
        [3,4]
    ]
)

M2 = torch.tensor(
    [
        [5,6],
        [7,8]
    ]
)

# Matrix multiplication of M1 and M2 
torch.matmul(M1,M2)

tensor([[19, 22],
        [43, 50]])

### Tensorflow

In [1]:
import tensorflow as tf

#### Calculate the dot product between the same vectors as above.

In [9]:
V3 = tf.constant([1, 2, 3])
V4 = tf.constant([6, 5, 4])


# Dot product of V3 and V4
tf.tensordot(V3, V4, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=28>

#### Calculate the matrix multiplication of the same matrics as above.


In [8]:
M3 = tf.constant(
    [
        [1,2],
        [3,4]
    ]
)
M4 = tf.constant(
    [
        [5,6],
        [7,8]
    ]
)

tf.matmul(M3, M4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [5]:
x = torch.tensor([
    [[1.,],[2.,]],
    [[3.,],[4.,]],
    ])

x.dim()

3